export const Localmovies = [
  {
    Title: 'Leo',
    Year: '2023',
    Rated: 'N/A',
    Released: '21 Nov 2023',
    Runtime: '164 min',
    Genre: 'Action, Crime, Drama',
    Director: 'Lokesh Kanagaraj',
    Writer: 'Lokesh Kanagaraj, Rathna Kumar, Deeraj Vaidy',
    Actors: 'Joseph Vijay, Trisha Krishnan, Sanjay Dutt',
    Plot: 'Parthiban is a mild mannered cafe owner in Kashmir, who fends off a gang of murderous thugs and gains attention from a drug cartel claiming he was once a part of them.',
    Language: 'Tamil',
    Country: 'India',
    Awards: 'N/A',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMDk0ZmVmMTktOGNiNS00Yzg5LWIzZTAtNjUxZWZhZDljY2Y0XkEyXkFqcGdeQXVyMTY1MzAyNjU4._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '7.9/10',
      },
    ],
    Metascore: 'N/A',
    imdbRating: '7.9',
    imdbVotes: '36,154',
    imdbID: 'tt15654328',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: '12th Fail',
    Year: '2023',
    Rated: 'N/A',
    Released: '27 Oct 2023',
    Runtime: '147 min',
    Genre: 'Biography, Drama',
    Director: 'Vidhu Vinod Chopra',
    Writer: 'Vidhu Vinod Chopra, Jaskunwar Kohli, Anurag Pathak',
    Actors: 'Vikrant Massey, Medha Shankar, Joshi Anantvijay',
    Plot: 'The real-life story of IPS Officer Manoj Kumar Sharma and IRS Officer Shraddha Joshi.',
    Language: 'Hindi, Malayalam, Tamil, Telugu, Kannada',
    Country: 'India',
    Awards: 'N/A',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNDY5YWMzOWEtNTVhZi00NTdmLWIxNGItN2Q5ZmIxNGRkZDYyXkEyXkFqcGdeQXVyMTYzMTU3Njgx._V1_SX300.jpg',
    Ratings: [{ Source: 'Internet Movie Database', Value: '9.3/10' }],
    Metascore: 'N/A',
    imdbRating: '9.3',
    imdbVotes: '5,608',
    imdbID: 'tt23849204',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Marvels',
    Year: '2023',
    Rated: 'PG-13',
    Released: '10 Nov 2023',
    Runtime: '105 min',
    Genre: 'Action, Adventure, Fantasy',
    Director: 'Nia DaCosta',
    Writer: 'Nia DaCosta, Megan McDonnell, Elissa Karasik',
    Actors: 'Brie Larson, Samuel L. Jackson, Zawe Ashton',
    Plot: 'Carol Danvers gets her powers entangled with those of Kamala Khan and Monica Rambeau, forcing them to work together to save the universe.',
    Language: 'English',
    Country: 'United States',
    Awards: 'N/A',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BM2U2YWU5NWMtOGI2Ni00MGMwLWFkNjItMjgyZWMxNjllNTMzXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
    Ratings: [],
    Metascore: 'N/A',
    imdbRating: 'N/A',
    imdbVotes: 'N/A',
    imdbID: 'tt10676048',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Japan',
    Year: '2023',
    Rated: 'N/A',
    Released: '10 Nov 2023',
    Runtime: 'N/A',
    Genre: 'Action, Drama, Thriller',
    Director: 'Raju Murugan',
    Writer: 'C. Murugesh Babu, Raju Murugan',
    Actors: 'Karthi, Sunil, Anu Emmanuel',
    Plot: 'A heist he commits at the house of a politician.',
    Language: 'Tamil, Kannada, Malayalam, Telugu, Hindi',
    Country: 'India',
    Awards: 'N/A',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZTlmODY5MWMtZDkyZi00YTU0LThiZWItZWFkYjJjYjFhZmEyXkEyXkFqcGdeQXVyMTA1OTMzNTQw._V1_SX300.jpg',
    Ratings: [],
    Metascore: 'N/A',
    imdbRating: 'N/A',
    imdbVotes: 'N/A',
    imdbID: 'tt23474462',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Bandra',
    Year: '2023',
    Rated: 'N/A',
    Released: '10 Nov 2023',
    Runtime: 'N/A',
    Genre: 'Action, Drama, Thriller',
    Director: 'Arun Gopy',
    Writer: 'Udaykrishnan',
    Actors: 'Tamannaah Bhatia, Dileep, Neil Nitin Mukesh',
    Plot: '',
    Language: 'Malayalam',
    Country: 'India',
    Awards: 'N/A',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZGY3ZWJlZjYtMDEzNy00YmU4LWI4M2MtNzcwODcwYjlkNzdiXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_SX300.jpg',
    Ratings: [],
    Metascore: 'N/A',
    imdbRating: 'N/A',
    imdbVotes: 'N/A',
    imdbID: 'tt21990434',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Salaar',
    Year: '2023',
    Rated: 'N/A',
    Released: '22 Dec 2023',
    Runtime: '170 min',
    Genre: 'Action, Drama, Thriller',
    Director: 'Prashanth Neel',
    Writer: 'Choudary Hanuman, Prashanth Neel, D.R. Suri',
    Actors: 'Prabhas, Prithviraj Sukumaran, Shruti Haasan',
    Plot: 'A gang leader tries to keep a promise made to his dying friend and takes on the other criminal gangs.',
    Language: 'Kannada, Malayalam, Tamil, Telugu',
    Country: 'India',
    Awards: 'N/A',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BODAyYjIzZDEtMjFkMy00OGE2LWEzODItYmE4NjhkNzYxNmRjXkEyXkFqcGdeQXVyMTUzNTgzNzM0._V1_SX300.jpg',
    Ratings: [],
    Metascore: 'N/A',
    imdbRating: 'N/A',
    imdbVotes: 'N/A',
    imdbID: 'tt13927994',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
];

export const Localtheaters = [
  {
    tname: 'INOX: Reliance Mall, Jalandhar',
    bookedslots: ['7:00 PM'],
    fastslots: ['9:05 PM', '10:30 PM'],
    availableslots: ['11:10 PM'],
  },
  {
    tname: 'PVR: Curo, Jalandhar',
    bookedslots: [],
    fastslots: [],
    availableslots: [
      '11:10 PM',
      '10:05 AM',
      '2:15 PM',
      '5:00 PM',
      '7:45 PM',
      '10:30 PM',
    ],
  },
];
